apiVersion: apps/v1
kind: Deployment
metadata:
  name: hobby-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hobbyservice
  template:
    metadata:
      labels:
        app: hobbyservice
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: hobbyservice
          image: docker.io/janinevansaaze/hobbyservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: hobbies-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: hobbyservice
  ports:
    - name: hobbyservice
      protocol: TCP
      port: 8080
      targetPort: 8080
#---
#apiVersion: autoscaling/v2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: hobby-hpa
#  namespace: default  
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: hobby-depl  
#  minReplicas: 1  # Minimum number of replicas 
#  maxReplicas: 10  # Maximum number of replicas 
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        target:
#          type: Utilization
#          averageUtilization: 50  # Scale if CPU usage exceeds 50%
#    - type: Resource
#      resource:
#        name: memory
#        target:
#          type: Utilization
#          averageUtilization: 50  # Scale if memory usage exceeds 50%